import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Auto-generate sidebar groups from directories present in _ingest/ at build time.
 * Each engine directory becomes a labelled sidebar group with autogenerated entries.
 * Returns an empty array if _ingest/ doesn't exist yet (e.g. during local dev without content).
 */
function buildSidebar() {
  const ingestDir = join(__dirname, 'src', 'content', '_ingest');
  if (!existsSync(ingestDir)) return [];

  const engines = readdirSync(ingestDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  return engines.map(engine => ({
    label: engine.charAt(0).toUpperCase() + engine.slice(1),
    autogenerate: { directory: engine },
  }));
}

export default defineConfig({
  // CODEX_SITE_URL is set per engine in CI (e.g. https://whittakertech.github.io/midas)
  site: process.env.CODEX_SITE_URL ?? 'http://localhost:4321',
  integrations: [
    starlight({
      title: 'WhittakerTech Docs',
      sidebar: buildSidebar(),
    }),
  ],
});
